export interface Vendor {
  id: string;
  companyName: string;
  industry: string;
  location: string;
  verificationStatus: "verified" | "pending";
  dateAdded: string;
}

export const vendors: Vendor[] = [
  {
    id: "1",
    companyName: "QuantumTech Solutions",
    industry: "Technology",
    location: "San Francisco, CA",
    verificationStatus: "verified",
    dateAdded: "2024-03-01",
  },
  {
    id: "2",
    companyName: "GreenSprout Manufacturing",
    industry: "Manufacturing",
    location: "Cleveland, OH",
    verificationStatus: "pending",
    dateAdded: "2024-02-18",
  },
  {
    id: "3",
    companyName: "MediCore Health Systems",
    industry: "Healthcare",
    location: "Boston, MA",
    verificationStatus: "verified",
    dateAdded: "2024-04-22",
  },
  {
    id: "4",
    companyName: "BlueRidge Construction",
    industry: "Construction",
    location: "Atlanta, GA",
    verificationStatus: "verified",
    dateAdded: "2024-05-12",
  },
  {
    id: "5",
    companyName: "Apex Financial Partners",
    industry: "Finance",
    location: "New York, NY",
    verificationStatus: "pending",
    dateAdded: "2024-01-30",
  },
  {
    id: "6",
    companyName: "EcoWare Packaging Inc.",
    industry: "Manufacturing",
    location: "Seattle, WA",
    verificationStatus: "verified",
    dateAdded: "2024-03-15",
  },
  {
    id: "7",
    companyName: "BrightPath Education",
    industry: "Education",
    location: "Austin, TX",
    verificationStatus: "pending",
    dateAdded: "2024-06-02",
  },
  {
    id: "8",
    companyName: "NextPhase Robotics",
    industry: "Technology",
    location: "Detroit, MI",
    verificationStatus: "verified",
    dateAdded: "2024-04-09",
  },
  {
    id: "9",
    companyName: "WellSpring Labs",
    industry: "Healthcare",
    location: "Chicago, IL",
    verificationStatus: "verified",
    dateAdded: "2024-03-27",
  },
  {
    id: "10",
    companyName: "Silverline Logistics",
    industry: "Logistics",
    location: "Phoenix, AZ",
    verificationStatus: "pending",
    dateAdded: "2024-05-03",
  },
  {
    id: "11",
    companyName: "CloudNova Hosting",
    industry: "Technology",
    location: "Denver, CO",
    verificationStatus: "verified",
    dateAdded: "2024-02-20",
  },
  {
    id: "12",
    companyName: "GoldenHarvest Organics",
    industry: "Agriculture",
    location: "Des Moines, IA",
    verificationStatus: "pending",
    dateAdded: "2024-01-10",
  },
  {
    id: "13",
    companyName: "CityBridge Engineering",
    industry: "Construction",
    location: "Minneapolis, MN",
    verificationStatus: "verified",
    dateAdded: "2024-06-06",
  },
  {
    id: "14",
    companyName: "CareFirst Diagnostics",
    industry: "Healthcare",
    location: "Philadelphia, PA",
    verificationStatus: "pending",
    dateAdded: "2024-04-15",
  },
  {
    id: "15",
    companyName: "Liberty Tech Works",
    industry: "Technology",
    location: "Charlotte, NC",
    verificationStatus: "verified",
    dateAdded: "2024-05-25",
  },
  {
    id: "16",
    companyName: "OceanView Textiles",
    industry: "Manufacturing",
    location: "Portland, OR",
    verificationStatus: "verified",
    dateAdded: "2024-02-28",
  },
  {
    id: "17",
    companyName: "UrbanPulse Media",
    industry: "Media",
    location: "Los Angeles, CA",
    verificationStatus: "pending",
    dateAdded: "2024-03-18",
  },
  {
    id: "18",
    companyName: "SafeTrack Cybersecurity",
    industry: "Technology",
    location: "Baltimore, MD",
    verificationStatus: "verified",
    dateAdded: "2024-04-01",
  },
  {
    id: "19",
    companyName: "FrostCore AI",
    industry: "Technology",
    location: "Salt Lake City, UT",
    verificationStatus: "pending",
    dateAdded: "2024-06-10",
  },
  {
    id: "20",
    companyName: "Helix BioMedicals",
    industry: "Healthcare",
    location: "San Diego, CA",
    verificationStatus: "verified",
    dateAdded: "2024-02-05",
  },
];
